// <auto-generated />
using System;
using FiorelloFront.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiorelloFront.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240515175413_TabelProducs")]
    partial class TabelProducs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FiorelloFront.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 5, 15, 21, 54, 13, 475, DateTimeKind.Local).AddTicks(5310),
                            Description = "Salam",
                            Image = "blog-feature-img-1.jpg",
                            IsDeleted = false,
                            Title = "Blog Ilgar"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 5, 15, 21, 54, 13, 475, DateTimeKind.Local).AddTicks(5330),
                            Description = "Salam",
                            Image = "blog-feature-img-3.jpg",
                            IsDeleted = false,
                            Title = "Blog Kmaran"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 5, 15, 21, 54, 13, 475, DateTimeKind.Local).AddTicks(5330),
                            Description = "Salam",
                            Image = "blog-feature-img-4.jpg",
                            IsDeleted = false,
                            Title = "Blog Orxan"
                        });
                });

            modelBuilder.Entity("FiorelloFront.Models.Experts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Experts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 5, 15, 21, 54, 13, 475, DateTimeKind.Local).AddTicks(5400),
                            Image = "h3-team-img-1.png",
                            IsDeleted = false,
                            Name = "CRYSTAL BROOKS",
                            Position = "Florist"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 5, 15, 21, 54, 13, 475, DateTimeKind.Local).AddTicks(5400),
                            Image = "h3-team-img-2.png",
                            IsDeleted = false,
                            Name = "SHIRLEY HARRIS",
                            Position = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 5, 15, 21, 54, 13, 475, DateTimeKind.Local).AddTicks(5410),
                            Image = "h3-team-img-3.png",
                            IsDeleted = false,
                            Name = "BEVERLY CLARK",
                            Position = "Florist"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 5, 15, 21, 54, 13, 475, DateTimeKind.Local).AddTicks(5410),
                            Image = "h3-team-img-4.png",
                            IsDeleted = false,
                            Name = "AMANDA WATKINS",
                            Position = "Florist"
                        });
                });

            modelBuilder.Entity("FiorelloFront.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Sliders");
                });

            modelBuilder.Entity("FiorelloFront.Models.SliderInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("SliderInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
